import{a as l,S as u,i as n}from"./assets/vendor-dNBuWDsd.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const f="55068921-c9c0644d1a9915f60fd1c8249";function d(s){return l.get("https://pixabay.com/api/",{params:{key:f,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(t=>t.data)}const c=document.querySelector(".gallery"),m=new u(".gallery a");function y(s){const t=s.map(o=>`
    <li class="gallery-item">
      <a href="${o.largeImageURL}">
        <img src="${o.webformatURL}" alt="${o.tags}" />
      </a>
      <p>❤️ ${o.likes} | 👁 ${o.views}</p>
    </li>
  `).join("");c.insertAdjacentHTML("beforeend",t),m.refresh()}function h(){c.innerHTML=""}function g(){document.querySelector(".loader").classList.add("show")}function p(){document.querySelector(".loader").classList.remove("show")}const L=document.querySelector(".form");L.addEventListener("submit",s=>{s.preventDefault();const t=s.target.elements["search-text"].value.trim();if(!t){n.error({message:"Please enter a search query"});return}h(),g(),d(t).then(o=>{if(o.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}y(o.hits)}).catch(()=>{n.error({message:"Something went wrong"})}).finally(()=>{p()})});
//# sourceMappingURL=index.js.map
